### ISSUE TITLE
Data files not included in release 0.9.1

### ISSUE THREAD

**Issue by slinkp** [fmarani/spam#1]
I wanted to try it out, but surbl can't be imported because it tries and fails to load data files at import time.
You need to fix your setup.py to include those.

> > > from spam.surbl import SurblChecker
> > >   Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/home/pw/tmp/spamfighter/local/lib/python2.7/site-packages/spam/surbl.py", line 8, in <module>
> > >     class SurblChecker(object):
> > >   File "/home/pw/tmp/spamfighter/local/lib/python2.7/site-packages/spam/surbl.py", line 14, in SurblChecker
> > >     two_level_file = open(join(abspath(dirname(**file**)) + "/two-level-tlds")),
> > >   IOError: [Errno 2] No such file or directory: '/home/pw/tmp/spamfighter/local/lib/python2.7/site-packages/spam/two-level-tlds'

**Comment by fmarani** [comment]
setup.py corrected, try the new version and let me know if it works..

**Comment by slinkp** [comment]
Looks good thanks!

On Fri, May 25, 2012 at 05:34:12PM -0700, Federico Marani wrote:

> setup.py corrected, try the new version and let me know if it works..
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fmarani/spam/issues/1#issuecomment-5943173

## 

Paul Winkler
